  server.port: 8082
  spring:
    datasource:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?currentSchema=food
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    profiles:
      active: ${cluster_env}
    flyway:
      schemas: food